### ISSUE TITLE
Add extra tracker effects

### ISSUE THREAD

**Issue by sm-Fifteen** [sm-Fifteen/SteamControllerTracker#11]
As it turns out, libopenMPT normalizes the effect IDs, so all that's needed is to find out which ones can be supported (considering we only have a pulse wave, so no volume or tremolo, n panning because no volume, and can't update it too often).

From `modcommand.h` :

- [x] CMD_ARPEGGIO			= 1
- [x] CMD_PORTAMENTOUP		= 2
- [x] CMD_PORTAMENTODOWN		= 3
- [ ] CMD_TONEPORTAMENTO		= 4
- [x] CMD_VIBRATO				= 5
- [x] CMD_PATTERNBREAK = 14 // Immediately jump to next pattern
- [ ] CMD_RETRIG				= 15 // Retrigger every n Ticks
- [x] CMD_SPEED				= 16
- [x] CMD_TEMPO				= 17
- [ ] CMD_KEYOFF				= 25 // Turn off after n Ticks

The rest mostly seem to be fine versions of existing commands, but I might have missed some.

**Comment by sm-Fifteen** [comment]
Vibrato is gonna need some more work, but it's *there*, so I'll mark it as done.

**Comment by Teteros** [comment]
`CMD_TEMPO` and `CMD_SPEED` would be really handy as some modules straight out sound wrong because they rely on those effect.

e.g: Start of Chain Chip https://youtu.be/5DRLLsBitIU?list=PLdKuLQHTZCh_j6mmfSSmlxOuHWuXbmUdK

What you already have is quite impressive and I'm having a blast with it!

**Comment by sm-Fifteen** [comment]
Yeah, I should probably priorise those two. Looking at your other videos, the pattern break command (`CMD_PATTERNBREAK = 14`) also breaks a few songs, so I added it to the list. I'll see if I can't find some time next week to add those three.

Glad you're having fun with it, in any case.
